spring:
  datasource:
    username: sa
    password: upitec
    url: jdbc:sqlserver://172.21.10.79:1433;DatabaseName=test_user_service

#  flyway:
#    baselineOnMigrate: true

remote:
  url: "http://localhost:8888"


